IMAGE_NAME = "ubuntu/jammy64"

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = IMAGE_NAME
    ubuntu.vm.hostname = "ubuntu"
    
    # Primární NAT/host-only
    ubuntu.vm.network "private_network", ip: "192.168.56.10"

    # Interní síť pro Zabbix komunikaci
    ubuntu.vm.network "private_network", ip: "192.168.1.3", virtualbox__intnet: "intnet"

    # Provisioning: kopírování a spuštění skriptů
    ubuntu.vm.provision "file", source: "id_rsa.pub", destination: "/home/vagrant/id_rsa.pub"

    ubuntu.vm.provision "shell", inline: <<-SHELL
      cat /home/vagrant/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
    SHELL

    # Spuštění instalačního a konfiguračního skriptu
    ubuntu.vm.provision "shell", path: "install-zabbix-agent2.sh"
    ubuntu.vm.provision "shell", path: "configure-zabbix-agent2.sh"
  end
end
